M: 4864
N: 2048
K: 4160
tuning:
  BLOCK_SIZE_M: 256
  BLOCK_SIZE_N: 128
  BLOCK_SIZE_K: 64
  GROUP_SIZE_M: 8
  waves_per_eu: 0
  num_warps: 4
  num_ctas: 1
  num_stages: 2
  matrix_instr_nonkdim: 16
  kpack: 1
  instruction_sched_variant: "none"
  #instruction_sched_variant: "local_prefetch"
